name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies (Ubuntu 24.04)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
            libncurses6 libncurses-dev libtinfo6 \
            gcc g++ make cmake autoconf automake pkg-config

      - name: Install Python deps (Cython + Buildozer)
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK + tools
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -e
          export ANDROID_SDK_ROOT="${GITHUB_WORKSPACE}/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;23.1.7779620"

      - name: Fix sdkmanager path for Buildozer
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          mkdir -p $ANDROID_SDK_ROOT/tools/bin
          ln -s $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager $ANDROID_SDK_ROOT/tools/bin/sdkmanager

      - name: Fix NDK path for Buildozer
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          ln -s $ANDROID_SDK_ROOT/ndk/23.1.7779620 $ANDROID_SDK_ROOT/ndk/android-ndk-r23b

      - name: Patch buildozer.spec to use SDK 33
        run: |
          SPEC=buildozer.spec
          sed -i 's|^android.api *=.*|android.api = 33|' "$SPEC" || echo 'android.api = 33' >> "$SPEC"
          sed -i 's|^android.sdk *=.*|android.sdk = 33|' "$SPEC" || echo 'android.sdk = 33' >> "$SPEC"
          sed -i 's|^android.build_tools *=.*|android.build_tools = 33.0.2|' "$SPEC" || echo 'android.build_tools = 33.0.2' >> "$SPEC"
          sed -i 's|^android.ndk *=.*|android.ndk = 23b|' "$SPEC" || echo 'android.ndk = 23b' >> "$SPEC"
          sed -i 's|^android.accept_sdk_license *=.*|android.accept_sdk_license = True|' "$SPEC" || echo 'android.accept_sdk_license = True' >> "$SPEC"
          echo "=== buildozer.spec config ==="
          grep -E '^(android.api|android.sdk|android.build_tools|android.ndk|android.accept_sdk_license)' "$SPEC"

      - name: Build APK (debug)
        env:
          ANDROIDSDK: ${{ github.workspace }}/android-sdk
          BUILDOZER_WARN_ON_ROOT: 1
          BUILDOZER_LOG_LEVEL: 2
        run: |
          rm -rf ~/.buildozer
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: emaktabauto-debug-apk
          path: bin/*.apk
